# Generated by Django 3.2.13 on 2022-06-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220616_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.PositiveIntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'))),
                ('quantity', models.PositiveIntegerField()),
                ('addressid', models.PositiveIntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address'))),
                ('sellerid', models.PositiveIntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller'))),
                ('selling_productid', models.PositiveBigIntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productseller'))),
                ('total', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
